# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.menu_builder:
        class: SocialBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@security.authorization_checker", "@doctrine.orm.entity_manager", "@security.token_storage"]

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ["@app.menu_builder", createMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
